version: '3.7'

services:
  pgadmin:
    image: dpage/pgadmin4:2021-05-18-1
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@article.com
      PGADMIN_DEFAULT_PASSWORD: "postgres"
    depends_on:
      - postgres
    ports:
      - 8090:80

  postgres:
    image: postgres:9.6.9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: article_database
